// <auto-generated />
namespace GoldMortgageApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class ECommerce03 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ECommerce03));
        
        string IMigrationMetadata.Id
        {
            get { return "201902171842115_E-Commerce03"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
